Document update
OpenIdentityPlatform/OpenDJ pull request #422
Opened 2024-10-05 03:47 UTC by JesseCoretta

Because the correct fix for the aforementioned issue will likely not be implemented, this is the document update I recommend. It only modifies a small part of this subsection.

2024-10-08 13:53 UTC, vharseko requested changes

2024-10-08 13:53 UTC, vharseko commented on opendj-doc-generated-ref/src/main/asciidoc/admin-guide/chap-schema.adoc
> +If and when this issue is resolved, the above schema DIT structure rule and name form definitions will become unnecessary and should be removed.
please provide reference to issue

2024-10-08 21:53 UTC, JesseCoretta commented on opendj-doc-generated-ref/src/main/asciidoc/admin-guide/chap-schema.adoc
> +If and when this issue is resolved, the above schema DIT structure rule and name form definitions will become unnecessary and should be removed.
https://github.com/OpenIdentityPlatform/OpenDJ/issues/425

2024-10-16 11:42 UTC, vharseko approved these changes

2024-10-17 10:28 UTC, JesseCoretta commented
I'm going to do yet another revision of this section to ensure the wording lines up with our intentions that we've agreed upon.  It will only take a few minutes...

2024-10-17 11:22 UTC, vharseko approved these changes

2024-10-17 11:52 UTC, maximthomas approved these changes

2024-10-17 12:30 UTC, merged